version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    container_name: wordpress-starter
    ports:
      - "80:80"      
    volumes:
      - ./:/app
    links:
       - db:db

  db:
    image: mysql
    container_name: db-wordpress-starter
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: wordpress 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-wordpress-starter
    environment:
       MYSQL_ROOT_PASSWORD: wordpress 
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini